app: serverless-trading-signal-processing
service: trading-signal-processing

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:GetObject
      Resource: arn:aws:s3:::${env:S3_INDICATORS_BUCKET}/*

functions:
  trading_view_strategy_signal:
    handler: handler.trading_view_strategy_signal
    events:
      - http:
          path: /trading-view-strategy-signal
          method: post

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
