app: serverless-trading-signal-processing
service: trading-signal-processing

provider:
  name: aws
  runtime: nodejs12.x

functions:
  trading_view_strategy_signal:
    handler: handler.trading_view_strategy_signal
    events:
      - http:
          path: /trading-view-strategy-signal
          method: post

plugins:
  - serverless-plugin-typescript
  - serverless-offline
